oneutka/apps/utka/urls.py
from django.urls import path

from . import views

app_name = 'utka'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('<int:utka_id>/', views.detail, name = 'detail'),
	path('<int:utka_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
]

# /utka/
# /utka/1/

oneutka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('utka/', include('utka.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

oneutka/apps/utka/models.py
import datetime
from django.db import models

from django.utils import timezone

class Utka(models.Model):
	utka_title = models.CharField("Название статьи", max_length=200)
	utka_text = models.TextField("Текст статьи")
	pub_date = models.DateTimeField("Дата публикации")

	def __str__(self):
		return self.utka_title

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

	class Meta:
		verbose_name = ("статью")
		verbose_name_plural = ("статьи")


class Comment(models.Model):
	utka = models.ForeignKey(Utka, on_delete=models.CASCADE)
	author_name = models.CharField("Имя автора", max_length=50)
	comment_text = models.CharField("Текст комментария", max_length=200)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = ("Комментарий")
		verbose_name_plural = ("Комментарии")

oneutka/apps/utka/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Utka

def index(request):
	latest_utka_list = Utka.objects.order_by('-pub_date')[:5]
	return render(request, 'utka/list.html', {'latest_utka_list': latest_utka_list})


def detail(request, utka_id):
	try:
		a = Utka.objects.get( id = utka_id )
	except:
		raise Http404('Статья не найдена!')

	latest_comment_list = a.comment_set.order_by('-id')[:10]

	return render(request, 'utka/detail.html', {'utka': a, 'latest_comment_list': latest_comment_list})


def leave_comment(request, utka_id):
	try:
		a = Utka.objects.get( id = utka_id )
	except:
		raise Http404('Статья не найдена!')
	
	a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

	return HttpResponseRedirect( reverse('utka:detail', args=(a.id,)) )

oneutka/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Визитка пользователя{% endblock %}</title>
  </head>
  <body>

    {% block content %}{% endblock %}

  </body>
</html>

oneutka/templates/utka/detail.html
{% extends 'base.html' %}

{% block title %}{{utka.utka_title}}{% endblock %}

{% block content %}

<h2>{{utka.utka_title}}</h2>

<p>{{utka.utka_text}}</p>

<em>{{utka.pub_date}}</em>

{% if utka.was_published_recently %}
[НОВАЯ СТАТЬЯ]
{% endif %}

<hr>

{% if latest_comment_list %}

	{% for c in latest_comment_list %}
		<p>
			<strong>{{c.author_name}}</strong>
			<p>{{c.comment_text}}</p>
		</p>
	{% endfor %}

{% else %}
Комментарии не найдены! Станьте первым :)
{% endif %}

<hr>

<form action="{% url 'utka:leave_comment' utka.id %}" method="POST">

	|{% csrf_token %}


	<input type="text" required placeholder="Ваше имя" name="name"><br>
	<textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

	<button type="submit">Оставить комментарий</button>

</form>

{% endblock %}

oneutka/templates/utka/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

	{% if latest_utka_list %}

		{% for a in latest_utka_list%}
			<a href="{% url 'utka:detail' a.id %}">{{a.utka_title}}</a>
		{% endfor %}

	{% else %}
		Статьи не найдены )=
	{% endif %}

{% endblock %}